"""cascade delete on user/session foreign keys

Revision ID: 773628c3638d
Revises: 2dffbe4fb8d4
Create Date: 2026-07-22 02:54:20.169119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '773628c3638d'
down_revision: Union[str, Sequence[str], None] = '2dffbe4fb8d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('interview_sessions_user_id_fkey'), 'interview_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'interview_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('question_evaluations_session_id_fkey'), 'question_evaluations', type_='foreignkey')
    op.create_foreign_key(None, 'question_evaluations', 'interview_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question_evaluations', type_='foreignkey')
    op.create_foreign_key(op.f('question_evaluations_session_id_fkey'), 'question_evaluations', 'interview_sessions', ['session_id'], ['id'])
    op.drop_constraint(None, 'interview_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('interview_sessions_user_id_fkey'), 'interview_sessions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
